(function() {var implementors = {};
implementors["feroxide"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"feroxide/struct.ELECTRON.html\" title=\"struct feroxide::ELECTRON\">ELECTRON</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"feroxide/data_ions/struct.HYDROXIDE.html\" title=\"struct feroxide::data_ions::HYDROXIDE\">HYDROXIDE</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"feroxide/data_ions/struct.AMMONIUM.html\" title=\"struct feroxide::data_ions::AMMONIUM\">AMMONIUM</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"feroxide/data_ions/struct.SULPHATE.html\" title=\"struct feroxide::data_ions::SULPHATE\">SULPHATE</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"feroxide/data_molecules/struct.WATER.html\" title=\"struct feroxide::data_molecules::WATER\">WATER</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"feroxide/data_molecules/struct.CO2.html\" title=\"struct feroxide::data_molecules::CO2\">CO2</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"feroxide/data_molecules/struct.AMMONIA.html\" title=\"struct feroxide::data_molecules::AMMONIA\">AMMONIA</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"feroxide/data_molecules/struct.SUGAR.html\" title=\"struct feroxide::data_molecules::SUGAR\">SUGAR</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">__Deref</a> for <a class=\"struct\" href=\"feroxide/data_sep/struct.SEPMAP.html\" title=\"struct feroxide::data_sep::SEPMAP\">SEPMAP</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
